Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Zaplať pojistku 1000."), { Effect::PLAYER, Effect::FEE, 1000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Pokuta za nedodržení předpisů 400."), { Effect::PLAYER, Effect::FEE, 400 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Renovuješ všechny stáje. Za každý svůj obsazený dostih zaplať 500."), { Effect::PLAYER, Effect::FEE_PER_RACE, 500, 500 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Mimořádný zisk z dostihů obdržíš 2.000."), { Effect::PLAYER, Effect::GAIN, 2000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Jako dárek k narozeninám obdržíš od každého 200."), { Effect::OTHER_PLAYERS, Effect::TRANSFER, 200 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Mimořádná prémie 500."), { Effect::PLAYER, Effect::GAIN, 500 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Obdržíš dotaci 4.000."), { Effect::PLAYER, Effect::GAIN, 4000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Zaplať dluh 3.000."), { Effect::PLAYER, Effect::FEE, 3000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Za každý svůj obsazený dostih zaplať 800, za každý svůj obsazený hlavní dostih sezóny zaplať 2.300."), { Effect::PLAYER, Effect::FEE_PER_RACE, 800, 2300 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Zaplať příspěvek 2.000."), { Effect::PLAYER, Effect::FEE, 2000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Nákup materiálu na opravu 100."), { Effect::PLAYER, Effect::FEE, 100 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Výhra v loterii 1.000."), { Effect::PLAYER, Effect::GAIN, 1000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Obdržíš dotaci 2.000."), { Effect::PLAYER, Effect::GAIN, 2000 } },
Card { QT_TRANSLATE_NOOP("Finance", "Finance"), QT_TRANSLATE_NOOP("Finance", "Z banky obdržíš přeplatek 3.000."), { Effect::PLAYER, Effect::GAIN, 3000 } }
