name: Build

on:
  push:
    branches:
      - '**'
  create:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  msvc:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build the application
      shell: bash
      run: |
        TAG_NAME=$(./get-tag-name.sh)
        export CMAKE_PREFIX_PATH="$Qt5_Dir/lib/cmake"
        export PATH="$Qt5_Dir/bin":"$PATH"
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../release -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release -- -m
    - name: Install the application    
      if: github.event_name == 'create'
      shell: bash
      run: |
        cd build
        cmake -P cmake_install.cmake
        mkdir -p release
        mv client/Release/Client.exe release/
    - name: windeployqt
      if: github.event_name == 'create'
      shell: bash
      run: |
        cd build/release
        $Qt5_Dir/bin/windeployqt.exe --verbose 2 --release --compiler-runtime --angle --qmldir ../.. Client.exe
    - name: Package the application
      if: github.event_name == 'create'
      shell: bash
      run: |
        cd build/release
        7z a release.zip *
    - name: Upload
      if: github.event_name == 'create'
      shell: bash
      run: |
        TAG_NAME=$(./get-tag-name.sh)
        ./upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} tag="$TAG_NAME" filename="build/release/release.zip" renameto="KarantenyADostihy-win-${TAG_NAME/v/}".zip

  mingw:
    runs-on: windows-2019
    if: false
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win32_mingw73
    - name: Build the application
      shell: bash
      run: |
        TAG_NAME=$(./get-tag-name.sh)
        export CMAKE_PREFIX_PATH="$Qt5_Dir/lib/cmake"
        export PATH="$Qt5_Dir/bin":"$PATH"
        mkdir build
        cd build
        cmake -DCMAKE_SH="CMAKE_SH-NOTFOUND" .. -G "MinGW Makefiles"
        cmake --build . VERBOSE=1
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Qt
      run: |
        sudo apt update
        sudo apt install libxss1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 qt5-default libqt5gui5 qttools5-dev-tools qttools5-dev libqt5webengine5 libqt5webenginecore5 libqt5webenginewidgets5 libqt5printsupport5 libqt5quickwidgets5 libqt5x11extras5 libxss1 patchelf binutils cmake pkg-config qtbase5-dev qtwebengine5-dev libqt5x11extras5-dev qtbase5-private-dev libssl-dev libxss-dev libxmu-dev
    - name: Build the application
      shell: bash
      run: |
        TAG_NAME=$(./get-tag-name.sh)
        mkdir build
        cd build
        cmake ..
        cmake --build . -- -j2

  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install the dependencies
      run: |
        brew install qt
        brew install openssl
        brew install cmake
    - name: Build the application
      run: |
        TAG_NAME=$(./get-tag-name.sh)
        mkdir build
        cd build
        export CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
        export OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/
        cmake ..
        make -j2
